package com.app.twiglydb.network;

/**
 * Created by naresh on 17/01/16.
 */
public enum ServerResponseCode {
    USER_NOT_FOUND,
    ITEM_NOT_FOUND,
    STORE_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    ORDER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    MOBILE_ALREADY_EXISTS,
    WRONG_PASSWORD,
    FORM_ERROR,
    LOGIN_REQUIRED,
    NOT_ALLOWED,
    SERVER_EXCEPTION,
    CACHE_ERROR,
    NO_ACTIVE_STORE,
    ITEM_SOLD_OUT,
    INVALID_ORDER_DETAIL,
    INVALID_DELIVERY_ZONE,
    NOT_ENOUGH_ITEMS_AVAILABLE,
    STORE_CLOSED,
    COUPON_NOT_FOUND,
    OK,
    GENERIC_ERROR,
    NO_PENDING_FEEDBACK,
    NO_VALID_COUPON_USER,
    COUPON_NOT_VALID,
    COUPON_EXPIRED,
    OTP_MAX_RETRY_REACHED,
    OTP_INVALID,
    INVALID_MOBILE,
    INVALID_EMAIL,
    CANCEL_NOT_ALLOWED,
    VERIFICATION_PENDING,
    INVALID_GCMID,
    INVALID_DELIVERY_TIME,
    INVALID_PAYMENT_OPTION,
    BATCHED_RESPONSE,;
}
